__default__:
  partition: 'standard' #MODIFY
  group: 'bhurwitz' #MODIFY
  M: 'kblumberg@email.arizona.edu' #MODIFY
  time: '24:00:00'
  n: "{threads}"
  #m: "{resources[mem_mb]}mb"
  o: 'out/{rule}.{wildcards}.out'
  e: 'err/{rule}.{wildcards}.err'
  N: "1" #-N same as --nodes=N
  mpc: "5gb"
  ntasks: "94"
